version: '2'

services:

  web:
    build: frontend
    ports:
     - "3000:3000"

  server:
    build: server
    ports:
     - "8888:8888"

  db:
    image: postgres

  redis:
    image: "redis:alpine"
