version: '2'

services:

  web:
    build: frontend
    ports:
     - "3000:3000"
    volumes:
     - ./frontend:/usr/src/app

  server:
    env_file: .env
    build: server
    ports:
     - "8888:8888"
    links:
    - db:db
    volumes:
    - ./server:/code

  db:
    env_file: .env
    image: mysql

  redis:
    image: "redis:alpine"
